version: '3'

services:
  mysql:
    container_name: mysql
    image: hkccr.ccs.tencentyun.com/buildx/hub:mysql-5.7
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
    networks:
      - database-network

  redis:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
