version: '3'

services:
  mysql:
    container_name: mysql
    image: registry.cn-hangzhou.aliyuncs.com/buildx/hub:mysql-5.7
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/backup
      - ./mysql/sh:/sh
    networks:
      - database-network

  # redis:
  #   image: registry.cn-hangzhou.aliyuncs.com/buildx/hub:redis-7.4
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  #   # appendonly 启用 AOF（Append-Only File）持久化机制
  #   # redis-cli -h 127.0.0.1 -p 6379 -a 123456
  #   command: ["redis-server","--appendonly","yes", "--requirepass", "123456"]
  #   volumes:
  #     - ./redis/data:/data
  #   networks:
  #     - database-network

networks:
  database-network:
    driver: bridge
