version: '3'
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redis-node-1
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redis-node-2
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redis-node-3
# 配置集群
# docker exec -it redis-node-1 redis-cli --cluster create 192.168.7.8:6381 192.168.7.8:6382 192.168.7.8:6383  192.168.7.8:6384  192.168.7.8:6385  192.168.7.8:6386  192.168.7.8:6387 --cluster-replicas 1
# 验证集群
# docker exec -it redis-node-1 redis-cli -c -p 6381 cluster info
services:
  redis-node-1:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-1
    networks:
      - database-redis-cluster
    ports:
      - 6381:6381
    volumes:
      - ./redis/conf/redis-1.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-2:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-2
    networks:
      - database-redis-cluster
    ports:
      - 6382:6382
    volumes:
      - ./redis/conf/redis-2.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-3:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-3
    networks:
      - database-redis-cluster
    ports:
      - 6383:6383
    volumes:
      - ./redis/conf/redis-3.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-4:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-4
    networks:
      - database-redis-cluster
    ports:
      - 6384:6384
    volumes:
      - ./redis/conf/redis-4.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-5:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-5
    networks:
      - database-redis-cluster
    ports:
      - 6385:6385
    volumes:
      - ./redis/conf/redis-5.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-6:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-6
    networks:
      - database-redis-cluster
    ports:
      - 6386:6386
    volumes:
      - ./redis/conf/redis-6.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-node-7:
    image: hkccr.ccs.tencentyun.com/buildx/hub:redis-7.4
    container_name: redis-node-7
    networks:
      - database-redis-cluster
    ports:
      - 6387:6387
    volumes:
      - ./redis/conf/redis-7.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]


networks:
  database-redis-cluster:
    driver: bridge
